os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: fK8536CfClhDB4ugnKO08/6bb/97NGXIsR/E8YI3e5tcML/5ExOM14ueNdhOUJSv
  matrix:
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm test
  - npm run build
  - npm run dist 
